[package]
name = "rust-cli-app-template"
version = "0.1.0"
edition = "2021"
description = "A template for creating Rust CLI apps with Clap."
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/DenisGorbachev/rust-cli-app-template"
repository = "https://github.com/DenisGorbachev/rust-cli-app-template"
readme = "README.md"
keywords = []
categories = []

[package.metadata.details]
title = "Rust CLI app template"
tagline = ""
summary = ""
announcement = ""
readme = { generate = false }

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
cli-util = { git = "https://github.com/DenisGorbachev/cli-util" }
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
derive-new = "0.7.0"
derive_more = { version = "2.0.1", features = ["full"] }
fmt-derive = "0.1.2"
helpful = { git = "https://github.com/DenisGorbachev/helpful" }
standard-traits = { git = "https://github.com/DenisGorbachev/standard-traits" }
strum = { version = "0.27.1", features = ["derive"] }
stub-macro = { version = "0.1.3" }
subtype = { git = "https://github.com/DenisGorbachev/subtype" }
tokio = { version = "1.43.1", features = ["macros", "fs", "net", "rt", "rt-multi-thread"] }

[package.metadata.cargo-machete]
ignored = [
    "derive-getters",
    "derive-new",
    "derive_more",
    "fmt-derive",
    "helpful",
    "standard-traits",
    "strum",
    "stub-macro",
    "subtype"
]
